language: python
python:
    - "3.5"
    - "3.6"

services:
    - docker

env:
    - MONGO=3.2 PYMONGO=">=3.2,<3.4" MOTOR=">=1.0,<1.1"
    - MONGO=3.2 PYMONGO=">=3.4,<3.6" MOTOR=">=1.1,<1.2"
    - MONGO=3.2 PYMONGO=">=3.6,<4"   MOTOR=">=1.2,<2"

    - MONGO=3.4 PYMONGO=">=3.4,<3.6" MOTOR=">=1.1,<1.2"
    - MONGO=3.4 PYMONGO=">=3.6,<4"   MOTOR=">=1.2,<2"

    - MONGO=3.6 PYMONGO=">=3.6,<4"   MOTOR=">=1.2,<2"

before_install:
    - docker run -d -p 127.0.0.1:27017:27017 mongo:$MONGO

install:
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check -U setuptools
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check -U pip
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check -U pytest pytest-cov coveralls
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check pymongo$PYMONGO motor$MOTOR
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check .

script:
    - py.test -v --cov yadm --cov-report term-missing

after_success:
    - coveralls
