os: linux
dist: focal

language: python
python:
    - "3.8"
    - "3.9"

services:
    - docker

env:
    - MONGO=4.2
    - MONGO=4.4

before_install:
    - docker run -d -p 127.0.0.1:27017:27017 mongo:$MONGO

install:
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check -U setuptools
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check -U pip
    - travis_retry pip install --retries=30 --timeout=5 --no-cache-dir --disable-pip-version-check '.[asyncio,test]'

script:
    - py.test -v --cov yadm --cov-report term-missing

after_success:
    - coveralls
