language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"

services:
    - mongodb

install:
    - python3 setup.py install
    - pip install python-coveralls pytest-cov

script:
    - py.test -v --cov yadm --cov-report term-missing

after_success:
    - coveralls
