language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"

services:
    - mongodb

env:
    - PYMONGO_VERSION=">=2.8,<2.9"
    - PYMONGO_VERSION=">=2.9,<3.0"
    - PYMONGO_VERSION=">=3.0,<3.1"
    - PYMONGO_VERSION=">=3.1,<3.2"
    - PYMONGO_VERSION=">=3.2"

install:
    - pip install -U pip
    - pip install -U pytest pytest-cov coveralls pymongo$PYMONGO_VERSION
    - python3 setup.py install

script:
    - py.test -v --cov yadm --cov-report term-missing

after_success:
    - coveralls
